export const createBigNumber = (mantissa, exponent) => ({
  mantissa,
  exponent,
});

const FIXTURE_LAST_UPDATE = 1700000000000;

const range = (count, mapper) => Array.from({ length: count }, (_, index) => mapper(index));

const createPcAutobuyerState = () => ({
  autobuyersOn: true,
  disableContinuum: false,
  reality: { mode: 0, rm: '1e12', glyph: 0, time: 0, shard: 0, isActive: true },
  eternity: { mode: 0, amount: '1e40', increaseWithMult: true, time: 1, xHighest: '1e30', isActive: true },
  bigCrunch: {
    cost: 1,
    interval: 150000,
    mode: 0,
    amount: '1e200',
    increaseWithMult: true,
    time: 1,
    xHighest: '1e180',
    isActive: true,
    lastTick: 0,
  },
  galaxy: {
    cost: 1,
    interval: 20000,
    limitGalaxies: false,
    maxGalaxies: 8,
    buyMax: true,
    buyMaxInterval: 0,
    isActive: true,
    lastTick: 0,
  },
  dimBoost: {
    cost: 1,
    interval: 4000,
    limitDimBoosts: false,
    maxDimBoosts: 12,
    limitUntilGalaxies: false,
    galaxies: 10,
    buyMaxInterval: 0,
    isActive: true,
    lastTick: 0,
  },
  tickspeed: {
    isUnlocked: true,
    cost: 1,
    interval: 500,
    mode: 1,
    isActive: true,
    lastTick: 0,
    isBought: true,
  },
  sacrifice: { multiplier: '2', isActive: true },
  antimatterDims: {
    all: range(8, (tier) => ({
      isUnlocked: true,
      cost: tier + 1,
      interval: 500 + (tier * 100),
      bulk: 10 + tier,
      mode: 1,
      isActive: true,
      lastTick: 0,
      isBought: true,
    })),
    isActive: true,
  },
  infinityDims: {
    all: range(8, () => ({ isActive: true, lastTick: 0 })),
    isActive: true,
  },
  timeDims: {
    all: range(8, () => ({ isActive: true, lastTick: 0 })),
    isActive: true,
  },
  replicantiGalaxies: { isActive: true },
  replicantiUpgrades: {
    all: range(3, () => ({ isActive: true, lastTick: 0 })),
    isActive: true,
  },
  timeTheorems: { isActive: true },
  dilationUpgrades: {
    all: range(3, () => ({ isActive: true, lastTick: 0 })),
    isActive: true,
  },
  blackHolePower: {
    all: range(2, () => ({ isActive: true })),
    isActive: true,
  },
  realityUpgrades: {
    all: range(5, () => ({ isActive: true })),
    isActive: true,
  },
  imaginaryUpgrades: {
    all: range(10, () => ({ isActive: true })),
    isActive: true,
  },
  darkMatterDims: { isActive: true, lastTick: 0 },
  ascension: { isActive: true, lastTick: 0 },
  annihilation: { isActive: true, multiplier: 1.05 },
  singularity: { isActive: true },
  ipMultBuyer: { isActive: true },
  epMultBuyer: { isActive: true },
});

const createPcRecords = () => ({
  gameCreatedTime: 1600000000000,
  totalTimePlayed: 100000000,
  timePlayedAtBHUnlock: 5000000,
  realTimePlayed: 90000000,
  realTimeDoomed: 0,
  fullGameCompletions: 1,
  previousRunRealTime: 123456,
  totalAntimatter: '1e1200',
  recentInfinities: range(10, (index) => [1000 + index, 900 + index, '1e100', '1e90', `I${index}`]),
  recentEternities: range(10, (index) => [5000 + index, 4500 + index, '1e60', '1e55', `E${index}`, '200']),
  recentRealities: range(10, (index) => [20000 + index, 18000 + index, '1e12', 500 + index, `R${index}`, 50, 20]),
  thisInfinity: { time: 0, realTime: 0, lastBuyTime: 0, maxAM: '1e1000', bestIPmin: '1e250', bestIPminVal: '1e245' },
  bestInfinity: { time: 1000, realTime: 900, bestIPminEternity: '1e200', bestIPminReality: '1e220' },
  thisEternity: {
    time: 0,
    realTime: 0,
    maxAM: '1e1000',
    maxIP: '1e250',
    bestIPMsWithoutMaxAll: '1e20',
    bestEPmin: '1e60',
    bestEPminVal: '1e55',
    bestInfinitiesPerMs: '1e6',
  },
  bestEternity: { time: 5000, realTime: 4500, bestEPminReality: '1e55' },
  thisReality: {
    time: 0,
    realTime: 0,
    maxAM: '1e1000',
    maxIP: '1e250',
    maxEP: '1e60',
    bestEternitiesPerMs: '1e4',
    maxReplicanti: '1e900',
    maxDT: '1e35',
    bestRSmin: 120,
    bestRSminVal: 110,
  },
  bestReality: {
    time: 20000,
    realTime: 18000,
    glyphStrength: 3.5,
    RM: '1e12',
    RMSet: [1, 2, 3],
    RMmin: '1e8',
    RMminSet: [2, 3, 4],
    glyphLevel: 500,
    glyphLevelSet: [3, 4, 5],
    bestEP: '1e60',
    bestEPSet: [4, 5, 6],
    speedSet: [1],
    iMCapSet: [2],
    laitelaSet: [3],
  },
});

const createPcRealityState = () => ({
  realityMachines: '1e12',
  maxRM: '1e13',
  imaginaryMachines: 1200,
  iMCap: 5000,
  glyphs: {
    active: [{ id: 1, type: 'power', level: 500, strength: 2.1, effects: 15 }],
    inventory: [{ id: 2, type: 'time', level: 450, strength: 1.8, effects: 7 }],
    sac: { power: 100, infinity: 80, time: 60, replication: 40, dilation: 20, effarig: 10, reality: 5 },
    undo: [{ id: 3, type: 'dilation', level: 400, strength: 1.5 }],
    sets: [{ name: 'Push', glyphs: [1, 2, 3] }],
    protectedRows: 2,
    filter: {
      select: 0,
      trash: 1,
      simple: 0,
      types: {
        power: { rarity: 70, score: 1000, effectCount: 4, specifiedMask: 15, effectScores: [10, 9, 8, 7] },
        infinity: { rarity: 65, score: 900, effectCount: 4, specifiedMask: 15, effectScores: [9, 8, 7, 6] },
        time: { rarity: 60, score: 800, effectCount: 4, specifiedMask: 15, effectScores: [8, 7, 6, 5] },
        replication: { rarity: 55, score: 700, effectCount: 4, specifiedMask: 15, effectScores: [7, 6, 5, 4] },
        dilation: { rarity: 50, score: 600, effectCount: 4, specifiedMask: 15, effectScores: [6, 5, 4, 3] },
        effarig: { rarity: 45, score: 500, effectCount: 4, specifiedMask: 15, effectScores: [5, 4, 3, 2] },
      },
    },
    createdRealityGlyph: true,
    cosmetics: {
      active: true,
      glowNotification: false,
      unlockedFromNG: ['power'],
      symbolMap: { power: '*' },
      colorMap: { power: '#f5d142' },
    },
  },
  initialSeed: 12345,
  seed: 67890,
  secondGaussian: 1000000,
  musicSeed: 23456,
  musicSecondGaussian: 1000000,
  rebuyables: { 1: 5, 2: 4, 3: 3, 4: 2, 5: 1 },
  upgradeBits: 1023,
  upgReqs: 511,
  imaginaryUpgradeBits: 255,
  imaginaryUpgReqs: 127,
  imaginaryRebuyables: { 1: 10, 2: 9, 3: 8, 4: 7, 5: 6, 6: 5, 7: 4, 8: 3, 9: 2, 10: 1 },
  reqLock: { reality: 0, imaginary: 0 },
  perks: [1, 2, 3],
  respec: false,
  showGlyphSacrifice: true,
  showSidebarPanel: 1,
  autoSort: 1,
  autoCollapse: true,
  autoAutoClean: true,
  applyFilterToPurge: false,
  moveGlyphsOnProtection: true,
  perkPoints: 25,
  unlockedEC: 12,
  autoEC: true,
  lastAutoEC: 10,
  partEternitied: '0.5',
  autoAchieve: true,
  gainedAutoAchievements: true,
  automator: {
    state: {
      mode: 'running',
      topLevelScript: 1,
      editorScript: 1,
      repeat: true,
      forceRestart: false,
      followExecution: true,
      stack: [{ script: 1, line: 2 }],
    },
    scripts: { 1: { name: 'farm', content: 'auto reality' } },
    constants: { targetRM: '1e12' },
    constantSortOrder: ['targetRM'],
    execTimer: 1200,
    type: 'text',
    forceUnlock: true,
    currentInfoPane: 0,
  },
  achTimer: 0,
  hasCheckedFilter: true,
});

const createPcCelestialsState = () => ({
  teresa: {
    pouredAmount: 1000,
    quoteBits: 3,
    unlockBits: 7,
    run: false,
    bestRunAM: '1e1000',
    bestAMSet: [1, 2, 3],
    perkShop: [1, 2, 3, 4, 5],
    lastRepeatedMachines: '1e9',
  },
  effarig: {
    relicShards: '1e6',
    unlockBits: 3,
    run: false,
    quoteBits: 2,
    glyphWeights: { ep: 25, repl: 25, dt: 25, eternities: 25 },
    autoAdjustGlyphWeights: true,
  },
  enslaved: {
    isStoring: false,
    stored: 100,
    isStoringReal: false,
    storedReal: 50,
    autoStoreReal: true,
    isAutoReleasing: false,
    quoteBits: 4,
    unlocks: [1, 2],
    run: false,
    completed: true,
    tesseracts: 3,
    hasSecretStudy: true,
    feltEternity: true,
    progressBits: 15,
    hintBits: 7,
    hintUnlockProgress: 2,
    glyphHintsGiven: 1,
    zeroHintTime: 0,
  },
  v: {
    unlockBits: 7,
    run: false,
    quoteBits: 3,
    runUnlocks: [1, 2, 3],
    goalReductionSteps: [0, 1, 2],
    STSpent: 12,
    runGlyphs: [[1, 2], [3, 4]],
    runRecords: [0, 1, 2],
    wantsFlipped: true,
  },
  ra: {
    pets: {
      teresa: { level: 10, memories: 100, memoryChunks: 20, memoryUpgrades: 2, chunkUpgrades: 1 },
      effarig: { level: 8, memories: 80, memoryChunks: 16, memoryUpgrades: 2, chunkUpgrades: 1 },
      enslaved: { level: 6, memories: 60, memoryChunks: 12, memoryUpgrades: 1, chunkUpgrades: 1 },
      v: { level: 5, memories: 50, memoryChunks: 10, memoryUpgrades: 1, chunkUpgrades: 0 },
    },
    alchemy: range(21, (index) => ({ amount: index * 10, reaction: index % 2 === 0 })),
    highestRefinementValue: { power: 10, infinity: 9, time: 8, replication: 7, dilation: 6, effarig: 5 },
    quoteBits: 3,
    momentumTime: 1200,
    unlockBits: 7,
    run: false,
    charged: [1, 2, 3],
    disCharge: false,
    peakGamespeed: 1000,
    petWithRemembrance: 'teresa',
  },
  laitela: {
    darkMatter: '1e40',
    maxDarkMatter: '1e45',
    run: false,
    quoteBits: 4,
    dimensions: range(4, (index) => ({
      amount: `1e${20 + index}`,
      intervalUpgrades: index + 1,
      powerDMUpgrades: index + 2,
      powerDEUpgrades: index + 3,
      timeSinceLastUpdate: index * 100,
      ascensionCount: index,
    })),
    entropy: 0,
    thisCompletion: 3600,
    fastestCompletion: 1800,
    difficultyTier: 2,
    upgrades: { 1: 1, 2: 1 },
    darkMatterMult: 2,
    darkEnergy: 500,
    singularitySorting: { displayResource: 0, sortResource: 0, showCompleted: 0, sortOrder: 0 },
    singularities: 4,
    singularityCapIncreases: 2,
    lastCheckedMilestones: 3,
    milestoneGlow: true,
  },
  pelle: {
    doomed: false,
    upgrades: [1, 2, 3],
    remnants: 50,
    realityShards: '1e6',
    records: { totalAntimatter: '1e1200', totalInfinityPoints: '1e250', totalEternityPoints: '1e60' },
    rebuyables: {
      antimatterDimensionMult: 1,
      timeSpeedMult: 2,
      glyphLevels: 3,
      infConversion: 4,
      galaxyPower: 5,
      galaxyGeneratorAdditive: 6,
      galaxyGeneratorMultiplicative: 7,
      galaxyGeneratorAntimatterMult: 8,
      galaxyGeneratorIPMult: 9,
      galaxyGeneratorEPMult: 10,
    },
    rifts: {
      vacuum: { fill: '1e3', active: false, reducedTo: 1 },
      decay: { fill: '1e4', active: false, percentageSpent: 0.25, reducedTo: 1 },
      chaos: { fill: 100, active: false, reducedTo: 1 },
      recursion: { fill: '1e5', active: false, reducedTo: 1 },
      paradox: { fill: '1e6', active: false, reducedTo: 1 },
    },
    progressBits: 3,
    galaxyGenerator: {
      unlocked: true,
      spentGalaxies: 10,
      generatedGalaxies: 5,
      phase: 1,
      sacrificeActive: false,
    },
    quoteBits: 2,
    collapsed: { upgrades: false, rifts: false, galaxies: false },
    showBought: true,
  },
});

const createPcOptionsState = () => ({
  news: { enabled: true, repeatBuffer: 40, AIChance: 0, speed: 1, includeAnimated: true },
  notation: 'Mixed scientific',
  notationDigits: { comma: 5, notation: 9 },
  sidebarResourceID: 0,
  retryChallenge: false,
  retryCelestial: false,
  showAllChallenges: false,
  cloudEnabled: true,
  hideGoogleName: false,
  showCloudModal: true,
  forceCloudOverwrite: false,
  syncSaveIntervals: true,
  hotkeys: true,
  themeClassic: 'Normal',
  themeModern: 'Normal',
  updateRate: 33,
  newUI: true,
  offlineProgress: true,
  loadBackupWithoutOffline: false,
  automaticTabSwitching: true,
  respecIntoProtected: false,
  offlineTicks: 100000,
  hibernationCatchup: true,
  statTabResources: 0,
  multiplierTab: { currTab: 0, showAltGroup: false, replacePowers: false },
  autosaveInterval: 30000,
  showTimeSinceSave: true,
  saveFileName: 'mobile-fixture',
  exportedFileCount: 1,
  hideCompletedAchievementRows: false,
  glyphTextColors: true,
  headerTextColored: false,
  showNewGlyphIcon: true,
  showUnequippedGlyphIcon: true,
  highContrastRarity: false,
  swapGlyphColors: false,
  hideAlterationEffects: false,
  ignoreGlyphEffects: true,
  ignoreGlyphLevel: true,
  ignoreGlyphRarity: true,
  glyphBG: 0,
  glyphBorders: true,
  showHintText: {
    showPercentage: true,
    achievements: true,
    achievementUnlockStates: true,
    challenges: true,
    studies: true,
    glyphEffectDots: true,
    realityUpgrades: true,
    perks: true,
    alchemy: true,
    glyphInfoType: 0,
    showGlyphInfoByDefault: false,
  },
  animations: {
    bigCrunch: true,
    eternity: true,
    dilation: true,
    tachyonParticles: true,
    reality: true,
    background: true,
    blobSnowflakes: 16,
    blobHole: false,
  },
  confirmations: {
    armageddon: true,
    sacrifice: true,
    challenges: true,
    exitChallenge: true,
    eternity: true,
    dilation: true,
    resetReality: true,
    glyphReplace: true,
    glyphSacrifice: true,
    autoClean: true,
    sacrificeAll: true,
    glyphSelection: true,
    glyphUndo: true,
    deleteGlyphSetSave: true,
    glyphRefine: true,
    bigCrunch: true,
    replicantiGalaxy: true,
    antimatterGalaxy: true,
    dimensionBoost: true,
    switchAutomatorMode: true,
    respecIAP: true,
  },
  awayProgress: {
    antimatter: true,
    dimensionBoosts: true,
    antimatterGalaxies: true,
    infinities: true,
    infinityPoints: true,
    replicanti: true,
    replicantiGalaxies: true,
    eternities: true,
    eternityPoints: true,
    tachyonParticles: true,
    dilatedTime: true,
    tachyonGalaxies: true,
    timeTheorems: true,
    achievementCount: true,
    realities: true,
    realityMachines: true,
    imaginaryMachines: true,
    relicShards: true,
    darkMatter: true,
    darkEnergy: true,
    singularities: true,
    celestialMemories: true,
    blackHole: true,
    realityShards: true,
  },
  hiddenTabBits: 0,
  hiddenSubtabBits: range(11, () => 0),
  lastOpenTab: 0,
  lastOpenSubtab: range(11, () => 0),
  perkLayout: 0,
  perkPhysicsEnabled: true,
  automatorEvents: { newestFirst: false, timestampType: 0, maxEntries: 200, clearOnReality: true, clearOnRestart: true },
  invertTTgenDisplay: false,
  autoRealityForFilter: false,
});

export const createNormalPcSave = () => ({
  antimatter: '10',
  dimensions: {
    antimatter: [
      { amount: '10', bought: 1, costBumps: 0 },
      { amount: '0', bought: 0, costBumps: 0 },
    ],
  },
  buyUntil10: true,
  sacrificed: '0',
  achievementBits: [0],
  secretAchievementBits: [0],
  challenge: {
    normal: { current: 0, completedBits: 0 },
  },
  infinity: {
    upgradeBits: 0,
  },
  auto: {
    autobuyersOn: true,
    tickspeed: { isActive: false, isBought: false },
    antimatterDims: { isActive: true },
  },
  infinityPoints: '0',
  infinities: '0',
  dimensionBoosts: 0,
  galaxies: 0,
  news: { seen: {} },
  lastUpdate: FIXTURE_LAST_UPDATE,
  matter: '1',
  chall2Pow: 1,
  chall3Pow: '0.01',
  chall9TickspeedCostBumps: 0,
  chall8TotalSacrifice: '1',
  ic2Count: 0,
  partInfinityPoint: 0,
  partInfinitied: 0,
  break: false,
  secretUnlocks: { themes: [] },
  shownRuns: { Infinity: true },
  requirementChecks: {
    infinity: { maxAll: false, noSacrifice: true, noAD8: true },
  },
  records: {
    totalAntimatter: '10',
    thisInfinity: { time: 0, maxAM: '10' },
    bestInfinity: { time: Number.MAX_VALUE },
  },
  speedrun: { isActive: false },
  IPMultPurchases: 0,
  version: 25,
  options: {
    notation: 'Mixed scientific',
    confirmations: { sacrifice: true, bigCrunch: true },
  },
  IAP: { enabled: false },
});

export const createInfinityPcSave = () => ({
  ...createNormalPcSave(),
  antimatter: '1e400',
  infinityPoints: '1e50',
  infinities: '25',
  infinityPower: '1e20',
  break: true,
  infinityUpgrades: ['timeMult', 'dimMult'],
  infinityRebuyables: [4, 2, 1],
  challenge: {
    normal: { current: 0, completedBits: 255 },
    infinity: { current: 0, completedBits: 15 },
  },
  auto: {
    ...createNormalPcSave().auto,
    bigCrunch: { isActive: true, mode: 'amount', amount: '1e40' },
  },
  replicanti: {
    unl: true,
    amount: '1',
    chance: 0.01,
    interval: 1000,
    galaxies: 0,
  },
  records: {
    ...createNormalPcSave().records,
    totalAntimatter: '1e400',
    bestInfinity: { time: 120000, bestIPminReality: '0' },
  },
});

export const createEternityPcSave = () => ({
  ...createInfinityPcSave(),
  eternityPoints: '1e20',
  eternities: '5',
  eternityUpgrades: [1, 2],
  epmultUpgrades: 3,
  timeShards: '1e12',
  dimensions: {
    ...createInfinityPcSave().dimensions,
    infinity: [{ amount: '1e25', bought: 2 }],
    time: [{ amount: '1e10', bought: 1 }],
  },
  timestudy: {
    theorem: 24,
    studies: [11, 21],
    presets: [{ name: 'Eternity push', studies: '11,21' }],
  },
  eternityChalls: {
    current: 0,
    completions: { 1: 1 },
  },
  dilation: {
    active: false,
    studies: [1],
    tachyonParticles: '0',
    dilatedTime: '0',
    upgrades: [],
  },
  records: {
    ...createInfinityPcSave().records,
    thisEternity: { time: 0, maxIP: '1e50' },
    bestEternity: { time: 240000 },
  },
});

export const createNormalAndroidSave = () => ({
  IAP: { enabled: false },
  achievements: [],
  antimatter: createBigNumber(1, 1),
  auto: {
    autobuyersOn: true,
    tickspeed: { isActive: false, isBought: false },
    antimatterDims: { isActive: true },
  },
  brake: false,
  buyUntil10: true,
  challenge: {
    normal: { current: 0, completedBits: 0 },
  },
  dimensionBoosts: 0,
  dimensions: {
    antimatter: [
      { amount: createBigNumber(1, 1), bought: 1 },
      { amount: createBigNumber(0, 0), bought: 0 },
    ],
  },
  galaxies: 0,
  infinities: createBigNumber(0, 0),
  infinityPoints: createBigNumber(0, 0),
  lastUpdate: FIXTURE_LAST_UPDATE,
  matter: createBigNumber(1, 0),
  news: { seen: [] },
  options: { notation: 'Scientific', theme: 'Normal' },
  partInfinitied: 0,
  partInfinityPoint: 0,
  records: {
    totalAntimatter: createBigNumber(1, 1),
    bestInfinity: { time: Number.MAX_VALUE },
  },
  sacrificed: createBigNumber(0, 0),
  secretAchievements: [],
  shownRuns: { Infinity: true },
  speedrun: { isActive: false },
  triggeredTabNotificationBits: 0,
  tutorialActive: true,
  tutorialState: 0,
  version: 30100100,
});

export const createInfinityAndroidSave = () => ({
  ...createNormalAndroidSave(),
  antimatter: createBigNumber(1, 400),
  bankedInfinities: createBigNumber(0, 0),
  bigCrunches: createBigNumber(2.5, 1),
  brake: true,
  breakInfinityRebuyables: [4, 2, 1],
  breakInfinityUpgradeBits: 7,
  challenge: {
    normal: { current: 0, completedBits: 255 },
    infinity: { current: 0, completedBits: 15 },
  },
  infinities: createBigNumber(2.5, 1),
  infinityPoints: createBigNumber(1, 50),
  infinityPower: createBigNumber(1, 20),
  infinityUpgradeBits: 15,
  ipMultUpgrades: 4,
  replicanti: {
    unl: true,
    amount: createBigNumber(1, 0),
    chanceUpgrades: 0,
    intervalUpgrades: 0,
    galaxies: 0,
  },
  records: {
    ...createNormalAndroidSave().records,
    totalAntimatter: createBigNumber(1, 400),
    bestInfinity: { time: 120000 },
  },
});

export const createEternityAndroidSave = () => ({
  ...createInfinityAndroidSave(),
  bigEternities: createBigNumber(5, 0),
  dimensions: {
    ...createInfinityAndroidSave().dimensions,
    infinity: [{ amount: createBigNumber(1, 25), bought: 2 }],
    time: [{ amount: createBigNumber(1, 10), bought: 1 }],
  },
  epMultUpgrades: 3,
  eternities: createBigNumber(5, 0),
  eternityPoints: createBigNumber(1, 20),
  eternityUpgradeBits: 3,
  timeShards: createBigNumber(1, 12),
  timestudy: {
    theorem: 24,
    studies: [11, 21],
  },
  dilation: {
    active: false,
    tachyonParticles: createBigNumber(0, 0),
    dilatedTime: createBigNumber(0, 0),
  },
});

export const createComprehensivePcSave = () => ({
  antimatter: '1e1000',
  dimensions: {
    antimatter: range(8, (tier) => ({ amount: `1e${100 - (tier * 5)}`, bought: 10 - tier, costBumps: Math.max(0, 2 - tier) })),
    infinity: range(8, (tier) => ({
      isUnlocked: true,
      bought: 5 + tier,
      amount: `1e${50 + tier}`,
      cost: `1e${80 + tier}`,
      baseAmount: tier,
    })),
    time: range(8, (tier) => ({ cost: `1e${10 + tier}`, amount: `1e${25 + tier}`, bought: 3 + tier })),
  },
  buyUntil10: true,
  sacrificed: '1e500',
  achievementBits: [1, 2, 3],
  secretAchievementBits: [1],
  infinityUpgrades: ['timeMult', 'dimMult'],
  infinityRebuyables: [10, 5],
  challenge: {
    normal: { current: 0, bestTimes: range(11, (index) => 1000 + index), completedBits: 255 },
    infinity: { current: 2, bestTimes: range(8, (index) => 2000 + index), completedBits: 127 },
    eternity: { current: 0, unlocked: 12, requirementBits: 7 },
  },
  infinity: {
    upgradeBits: 255,
    upgrades: ['skipReset1'],
  },
  auto: createPcAutobuyerState(),
  infinityPoints: '1e250',
  infinities: '1000',
  infinitiesBanked: '50',
  dimensionBoosts: 12,
  galaxies: 8,
  news: {
    seen: { a1: true, lategame: true },
    specialTickerData: { uselessNewsClicks: 2, paperclips: 100, newsQueuePosition: 10, eiffelTowerChapter: 1 },
    totalSeen: 2,
  },
  lastUpdate: 1700000000000,
  matter: '1e20',
  chall2Pow: 1.25,
  chall3Pow: '1e12',
  chall9TickspeedCostBumps: 3,
  chall8TotalSacrifice: '1e30',
  ic2Count: 4,
  partInfinityPoint: 0.5,
  partInfinitied: 0.25,
  break: true,
  secretUnlocks: { themes: ['S1'], viewSecretTS: true, cancerAchievements: false },
  shownRuns: { Reality: true, Eternity: true, Infinity: true, reality: true },
  requirementChecks: {
    infinity: { maxAll: false, noSacrifice: false, noAD8: true },
    eternity: { onlyAD1: true, onlyAD8: true, noAD1: false, noRG: true },
    reality: {
      noAM: false,
      noTriads: true,
      noPurchasedTT: false,
      noInfinities: false,
      noEternities: false,
      noContinuum: true,
      maxID1: '1e50',
      maxStudies: 120,
      maxGlyphs: 4,
      slowestBH: 1,
    },
    permanent: { emojiGalaxies: 1, singleTickspeed: 0, perkTreeDragging: 1 },
  },
  records: createPcRecords(),
  speedrun: {
    isUnlocked: true,
    isActive: false,
    isSegmented: false,
    usedSTD: false,
    hasStarted: true,
    hideInfo: false,
    displayAllMilestones: true,
    startDate: 1600000000000,
    name: 'fixture',
    offlineTimeUsed: 0,
    records: range(26, (index) => index),
    achievementTimes: { r11: 1000 },
    seedSelection: 0,
    initialSeed: 12345,
    previousRuns: { fixture: { time: 123456 } },
  },
  IPMultPurchases: 12,
  version: 14,
  infinityPower: '1e90',
  postC4Tier: 7,
  eternityPoints: '1e60',
  eternities: '200',
  eternityUpgrades: [1, 2, 3],
  epmultUpgrades: 9,
  timeShards: '1e75',
  totalTickGained: 200,
  totalTickBought: 150,
  replicanti: {
    unl: true,
    amount: '1e900',
    chance: 0.12,
    chanceCost: '1e150',
    interval: 250,
    intervalCost: '1e140',
    boughtGalaxyCap: 10,
    galaxies: 20,
    galCost: '1e170',
  },
  timestudy: {
    studies: [11, 21, 31],
    theorem: 120,
    maxTheorem: 150,
    amBought: 10,
    ipBought: 20,
    epBought: 30,
    shopMinimized: false,
    preferredPaths: [[11, 21, 31], 0],
    presets: [{ name: 'Push', studies: '11,21,31' }],
  },
  eternityChalls: {
    current: 0,
    completions: { 1: 5, 2: 3 },
  },
  respec: false,
  eterc8ids: 2,
  eterc8repl: 1,
  dilation: {
    active: false,
    studies: [1, 2, 3],
    tachyonParticles: '1e30',
    dilatedTime: '1e35',
    nextThreshold: '1e40',
    baseTachyonGalaxies: 4,
    totalTachyonGalaxies: 8,
    upgrades: [4, 5],
    rebuyables: { 1: 5, 2: 4, 3: 3, 11: 2, 12: 1, 13: 1 },
    lastEP: '1e60',
  },
  realities: '25',
  partSimulatedReality: 0.75,
  reality: createPcRealityState(),
  blackHole: [
    { unlocked: true, active: true, intervalUpgrades: 2, powerUpgrades: 3, durationUpgrades: 4 },
    { unlocked: true, active: false, intervalUpgrades: 1, powerUpgrades: 2, durationUpgrades: 3 },
  ],
  blackHolePause: false,
  blackHoleAutoPauseMode: 0,
  blackHolePauseTime: 0,
  blackHoleNegative: 0,
  celestials: createPcCelestialsState(),
  isGameEnd: false,
  tabNotifications: ['reality'],
  triggeredTabNotificationBits: 2,
  tutorialState: 3,
  tutorialActive: false,
  options: createPcOptionsState(),
  IAP: { enabled: false },
});

export const createComprehensiveAndroidSave = () => ({
  IAP: { enabled: false },
  achievements: [1, 2, 3],
  antimatter: createBigNumber(1, 1000),
  auto: {
    dimensions: [{ isActive: true, bulk: 10 }],
    bigCrunch: { isActive: true, amount: createBigNumber(1, 200) },
  },
  bankedInfinities: createBigNumber(5, 1),
  bigCrunches: createBigNumber(1, 3),
  bigEternities: createBigNumber(2, 2),
  bigRealities: createBigNumber(3, 1),
  blackHole: [
    { unlocked: true, active: true, intervalUpgrades: 2, powerUpgrades: 3 },
  ],
  blackHoleAutoPauseMode: 0,
  blackHoleNegative: 0,
  blackHolePause: false,
  blackHolePauseTime: 0,
  brake: true,
  breakInfinityRebuyables: [10, 5],
  breakInfinityUpgradeBits: 12,
  buyUntil10: true,
  celestials: {
    teresa: { pouredAmount: createBigNumber(1, 8) },
    ra: { pets: { teresa: { level: 10 } } },
  },
  challenge: {
    normal: { current: 0, completedBits: 255 },
    infinity: { current: 0, completedBits: 127 },
  },
  dilation: {
    active: false,
    tachyonParticles: createBigNumber(1, 30),
    dilatedTime: createBigNumber(1, 35),
  },
  dimensionBoosts: 12,
  dimensions: {
    antimatter: [
      { amount: createBigNumber(1, 100), bought: 10 },
      { amount: createBigNumber(1, 80), bought: 8 },
    ],
    infinity: [{ amount: createBigNumber(1, 50), bought: 5 }],
    time: [{ amount: createBigNumber(1, 25), bought: 3 }],
  },
  epMultUpgrades: 9,
  eternities: createBigNumber(2, 2),
  eternityPoints: createBigNumber(1, 60),
  eternityUpgradeBits: 7,
  galaxies: 8,
  highestTierBoughtThisDimboost: 7,
  infinities: createBigNumber(1, 3),
  infinityPoints: createBigNumber(1, 250),
  infinityPower: createBigNumber(1, 90),
  infinityUpgradeBits: 15,
  ipMultUpgrades: 12,
  isGameEnd: false,
  lastUpdate: 1700000000000,
  matter: createBigNumber(1, 20),
  news: { seen: ['a1'] },
  options: { notation: 'Scientific', theme: 'Normal' },
  partInfinitied: 0.25,
  partInfinityPoint: 0.5,
  realities: createBigNumber(2.5, 1),
  reality: {
    realityMachines: createBigNumber(1, 12),
    imaginaryMachines: 1200,
    glyphs: {
      active: [{ id: 1, type: 'power', level: 500, strength: 2.1 }],
    },
    perks: [1, 2, 3],
  },
  records: {
    totalAntimatter: createBigNumber(1, 1200),
    bestInfinity: { time: 1000 },
  },
  replicanti: {
    unl: true,
    amount: createBigNumber(1, 900),
    chanceUpgrades: 12,
    intervalUpgrades: 10,
    galaxies: 20,
  },
  requirementChecks: { reality: { noEternities: false } },
  respec: false,
  sacrificed: createBigNumber(1, 500),
  secretAchievements: [1],
  secretUnlocks: { themes: ['S1'] },
  shownRuns: { reality: true },
  speedrun: { isActive: false },
  timeShards: createBigNumber(1, 75),
  timestudy: {
    studies: [11, 21, 31],
    theorem: 120,
  },
  totalTickBought: 150,
  totalTickGained: 200,
  triggeredTabNotificationBits: 2,
  tutorialActive: false,
  tutorialState: 3,
  usedUnpause: false,
  version: 30100100,
});
