export const createBigNumber = (mantissa, exponent) => ({
  mantissa,
  exponent,
});

export const createComprehensivePcSave = () => ({
  antimatter: '1e1000',
  dimensions: {
    antimatter: [
      { amount: '1e100', bought: 10, costBumps: 2 },
      { amount: '1e80', bought: 8, costBumps: 1 },
    ],
    infinity: [{ amount: '1e50', bought: 5 }],
    time: [{ amount: '1e25', bought: 3 }],
  },
  buyUntil10: true,
  sacrificed: '1e500',
  achievementBits: [1, 2, 3],
  secretAchievementBits: [1],
  infinityUpgrades: ['timeMult', 'dimMult'],
  infinityRebuyables: [10, 5],
  challenge: {
    normal: { current: 0, completedBits: 255 },
    infinity: { current: 2, completedBits: 127 },
  },
  infinity: {
    upgrades: ['skipReset1'],
  },
  auto: {
    dimensions: [{ isActive: true, bulk: 10 }],
    tickspeed: { isActive: true },
    bigCrunch: { isActive: true, mode: 'amount', amount: '1e200' },
  },
  infinityPoints: '1e250',
  infinities: '1000',
  infinitiesBanked: '50',
  dimensionBoosts: 12,
  galaxies: 8,
  news: { seen: ['a1'] },
  lastUpdate: 1700000000000,
  matter: '1e20',
  chall2Pow: 1.25,
  chall3Pow: '1e12',
  chall9TickspeedCostBumps: 3,
  chall8TotalSacrifice: '1e30',
  ic2Count: 4,
  partInfinityPoint: 0.5,
  partInfinitied: 0.25,
  break: true,
  secretUnlocks: { themes: ['S1'] },
  shownRuns: { reality: true },
  requirementChecks: {
    infinity: { noSacrifice: false },
    eternity: { onlyAD1: true },
    reality: { noEternities: false },
  },
  records: {
    totalAntimatter: '1e1200',
    bestInfinity: { time: 1000, realTime: 900 },
    bestEternity: { time: 5000 },
    bestReality: { time: 20000 },
  },
  speedrun: { isActive: false, records: {} },
  IPMultPurchases: 12,
  version: 14,
  infinityPower: '1e90',
  postC4Tier: 7,
  eternityPoints: '1e60',
  eternities: '200',
  eternityUpgrades: [1, 2, 3],
  epmultUpgrades: 9,
  timeShards: '1e75',
  totalTickGained: 200,
  totalTickBought: 150,
  replicanti: {
    unl: true,
    amount: '1e900',
    chance: 0.12,
    interval: 250,
    galaxies: 20,
  },
  timestudy: {
    studies: [11, 21, 31],
    theorem: 120,
    presets: [{ name: 'Push', studies: '11,21,31' }],
  },
  eternityChalls: {
    current: 0,
    completions: { 1: 5, 2: 3 },
  },
  respec: false,
  eterc8ids: 2,
  eterc8repl: 1,
  dilation: {
    active: false,
    studies: [1, 2, 3],
    tachyonParticles: '1e30',
    dilatedTime: '1e35',
    upgrades: [4, 5],
  },
  realities: '25',
  partSimulatedReality: 0.75,
  reality: {
    realityMachines: '1e12',
    imaginaryMachines: 1200,
    glyphs: {
      active: [{ id: 1, type: 'power', level: 500, strength: 2.1 }],
      inventory: [{ id: 2, type: 'time', level: 450, strength: 1.8 }],
      protectedRows: 2,
    },
    perks: [1, 2, 3],
    automator: { state: { mode: 'running' }, scripts: { 1: { name: 'farm', content: 'auto reality' } } },
  },
  blackHole: [
    { unlocked: true, active: true, intervalUpgrades: 2, powerUpgrades: 3, durationUpgrades: 4 },
    { unlocked: true, active: false, intervalUpgrades: 1, powerUpgrades: 2, durationUpgrades: 3 },
  ],
  blackHolePause: false,
  blackHoleAutoPauseMode: 0,
  blackHolePauseTime: 0,
  blackHoleNegative: 0,
  celestials: {
    teresa: { pouredAmount: 1000, rmStore: '1e9' },
    effarig: { relicShards: '1e6', unlockBits: 3 },
    enslaved: { isStoring: false, stored: 100 },
    v: { runUnlocks: [1, 2], goalReductionSteps: [0, 1] },
    ra: { pets: { teresa: { level: 10 }, effarig: { level: 8 } } },
    laitela: { matter: '1e40', darkMatterMult: 2 },
    pelle: { doomed: false, remnants: 50 },
  },
  isGameEnd: false,
  tabNotifications: ['reality'],
  triggeredTabNotificationBits: 2,
  tutorialState: 3,
  tutorialActive: false,
  options: {
    notation: 'Scientific',
    theme: 'Normal',
    confirmations: { glyphSacrifice: true },
  },
  IAP: { enabled: false },
});

export const createComprehensiveAndroidSave = () => ({
  IAP: { enabled: false },
  achievements: [1, 2, 3],
  antimatter: createBigNumber(1, 1000),
  auto: {
    dimensions: [{ isActive: true, bulk: 10 }],
    bigCrunch: { isActive: true, amount: createBigNumber(1, 200) },
  },
  bankedInfinities: createBigNumber(5, 1),
  bigCrunches: createBigNumber(1, 3),
  bigEternities: createBigNumber(2, 2),
  bigRealities: createBigNumber(3, 1),
  blackHole: [
    { unlocked: true, active: true, intervalUpgrades: 2, powerUpgrades: 3 },
  ],
  blackHoleAutoPauseMode: 0,
  blackHoleNegative: 0,
  blackHolePause: false,
  blackHolePauseTime: 0,
  brake: true,
  breakInfinityRebuyables: [10, 5],
  breakInfinityUpgradeBits: 12,
  buyUntil10: true,
  celestials: {
    teresa: { pouredAmount: createBigNumber(1, 8) },
    ra: { pets: { teresa: { level: 10 } } },
  },
  challenge: {
    normal: { current: 0, completedBits: 255 },
    infinity: { current: 0, completedBits: 127 },
  },
  dilation: {
    active: false,
    tachyonParticles: createBigNumber(1, 30),
    dilatedTime: createBigNumber(1, 35),
  },
  dimensionBoosts: 12,
  dimensions: {
    antimatter: [
      { amount: createBigNumber(1, 100), bought: 10 },
      { amount: createBigNumber(1, 80), bought: 8 },
    ],
    infinity: [{ amount: createBigNumber(1, 50), bought: 5 }],
    time: [{ amount: createBigNumber(1, 25), bought: 3 }],
  },
  epMultUpgrades: 9,
  eternities: createBigNumber(2, 2),
  eternityPoints: createBigNumber(1, 60),
  eternityUpgradeBits: 7,
  galaxies: 8,
  highestTierBoughtThisDimboost: 7,
  infinities: createBigNumber(1, 3),
  infinityPoints: createBigNumber(1, 250),
  infinityPower: createBigNumber(1, 90),
  infinityUpgradeBits: 15,
  ipMultUpgrades: 12,
  isGameEnd: false,
  lastUpdate: 1700000000000,
  matter: createBigNumber(1, 20),
  news: { seen: ['a1'] },
  options: { notation: 'Scientific', theme: 'Normal' },
  partInfinitied: 0.25,
  partInfinityPoint: 0.5,
  realities: createBigNumber(2.5, 1),
  reality: {
    realityMachines: createBigNumber(1, 12),
    imaginaryMachines: 1200,
    glyphs: {
      active: [{ id: 1, type: 'power', level: 500, strength: 2.1 }],
    },
    perks: [1, 2, 3],
  },
  records: {
    totalAntimatter: createBigNumber(1, 1200),
    bestInfinity: { time: 1000 },
  },
  replicanti: {
    unl: true,
    amount: createBigNumber(1, 900),
    chanceUpgrades: 12,
    intervalUpgrades: 10,
    galaxies: 20,
  },
  requirementChecks: { reality: { noEternities: false } },
  respec: false,
  sacrificed: createBigNumber(1, 500),
  secretAchievements: [1],
  secretUnlocks: { themes: ['S1'] },
  shownRuns: { reality: true },
  speedrun: { isActive: false },
  timeShards: createBigNumber(1, 75),
  timestudy: {
    studies: [11, 21, 31],
    theorem: 120,
  },
  totalTickBought: 150,
  totalTickGained: 200,
  triggeredTabNotificationBits: 2,
  tutorialActive: false,
  tutorialState: 3,
  usedUnpause: false,
  version: 30100100,
});
